name: Deploy DAGs to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install -y ssh

    - name: Copy DAGs to AWS EC2
      env:
        AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
        AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
        AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
      run: |
         mkdir -p ~/.ssh
         echo "${AWS_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dags/ ${AWS_EC2_USER}@${AWS_EC2_IP}:/home/ubuntu/dags/
